### ISSUE TITLE
Violation of Font Awesome License Agreement

### ISSUE THREAD

**Issue by alexpoiry** [niyazialpay/AlphaBlog#3]
My name is Alex and I'm head of cybersecurity for Font Awesome.

It appears that you are hosting all our pro assets on your repository in a way that is publicly searchable. This violates the terms of our license agreement. I'd like to discuss options with you about how we might remedy this. I do not believe your primary intent is illegal redistribution of our assets but that is effectively what is happening.

Please respond to this issue so we can discuss alternatives or make these assets private.

My preference is that we come to some mutually beneficial solution; however, if you do not respond to this I will have to use the DMCA option. Please respond as soon as possible.

**Comment by niyazialpay** [comment]
Hello, I will remove it from the repo as soon as possible.

**Comment by niyazialpay** [comment]
I removed from all branches, you can check it.

**Comment by alexpoiry** [comment]
Thank you very much for your prompt action.  If you have questions about the best ways to use Font Awesome we're more than happy to help with that, you can reach out me directly or send something to help@fontawesome.com.
